#!/usr/bin/env python3
"""
Project Halcyon — per-deploy secret & vulnerability-path randomizer.

Run once, BEFORE any VM provisioning, by scripts/deploy.sh. Deterministic given
the same --seed (useful for CI/debugging), but scripts/deploy.sh normally passes
a fresh random seed on every real deploy so no two labs are identical.

Outputs:
  ansible/group_vars/secrets_seed.yml   - consumed by all provisioning roles
  docs/answer-key.md                    - human-readable solution key (gitignored)

Neither output is meant to be committed to git.
"""
import argparse
import hashlib
import random
import secrets
import string
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
ALL_VARS = REPO_ROOT / "ansible" / "group_vars" / "all.yml"
SEED_OUT = REPO_ROOT / "ansible" / "group_vars" / "secrets_seed.yml"
ANSWER_KEY_OUT = REPO_ROOT / "docs" / "answer-key.md"

WORDLIST = [
    "harbor", "compass", "lantern", "cedar", "granite", "meridian", "amber",
    "falcon", "quartz", "ember", "birch", "sable", "cobalt", "willow", "tundra",
    "onyx", "marble", "cinder", "sparrow", "delta", "ridge", "hollow", "brisk",
    "vessel", "anchor", "signal", "current", "harvest", "outpost", "beacon",
]


def rng_from_seed(seed: str) -> random.Random:
    digest = hashlib.sha256(seed.encode()).digest()
    return random.Random(int.from_bytes(digest, "big"))


def gen_password(rng: random.Random, crackable: bool) -> str:
    """crackable=True -> a rockyou-adjacent pattern a wordlist+rules attack will hit,
    but not a bare dictionary word. crackable=False -> a strong service password."""
    if crackable:
        word = rng.choice(WORDLIST).capitalize()
        num = rng.randint(1, 999)
        suffix = rng.choice(["!", "#", "@", ""])
        return f"{word}{num}{suffix}"
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    return "".join(rng.choice(alphabet) for _ in range(20))


def gen_flag(rng: random.Random, stage: str) -> str:
    token = "".join(rng.choice(string.hexdigits.lower()) for _ in range(24))
    return f"HALCYON{{{stage}_{token}}}"


def select_live_paths(rng: random.Random, vuln_paths: dict, min_adcs: int, min_optional: int):
    always = [k for k, v in vuln_paths.items() if v.get("always")]
    optional = {k: v for k, v in vuln_paths.items() if not v.get("always")}

    adcs_optional = [k for k, v in optional.items() if v["category"] == "adcs"]
    other_optional = [k for k, v in optional.items() if v["category"] != "adcs"]

    live_adcs = rng.sample(adcs_optional, k=min(min_adcs, len(adcs_optional)))
    remaining_needed = max(0, min_optional - len(live_adcs))
    live_other = rng.sample(other_optional, k=min(remaining_needed, len(other_optional)))

    return sorted(set(always + live_adcs + live_other))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", default=None, help="deploy seed; random if omitted")
    args = ap.parse_args()

    seed = args.seed or secrets.token_hex(16)
    rng = rng_from_seed(seed)

    all_vars = yaml.safe_load(ALL_VARS.read_text())
    vuln_paths = all_vars["vuln_paths"]

    live_paths = select_live_paths(
        rng, vuln_paths,
        all_vars["randomize_min_adcs_live"],
        all_vars["randomize_min_optional_live"],
    )

    creds = {}
    for acct in all_vars["service_accounts"]:
        crackable = bool(acct.get("kerberoastable") or acct.get("asrep_roastable"))
        creds[acct["sam"]] = gen_password(rng, crackable=crackable)
    for u in all_vars["staff_users"]:
        creds[u["sam"]] = gen_password(rng, crackable=True)

    # local admin, shared across WS01/WS02 ONLY if the laps_absent_pth path is live
    # (this is the thing that makes that path meaningful when active).
    local_admin_pw = gen_password(rng, crackable=False)

    da_break_glass_pw = gen_password(rng, crackable=False)
    sa_mssql_pw = gen_password(rng, crackable=False)

    flags = {
        "web_foothold": gen_flag(rng, "web_foothold"),
        "linux_root": gen_flag(rng, "linux_root"),
        "first_domain_cred": gen_flag(rng, "first_domain_cred"),
        "privilege_escalation": gen_flag(rng, "priv_esc"),
        "domain_admin": gen_flag(rng, "domain_admin"),
    }

    seed_data = {
        "halcyon_deploy_seed": seed,
        "halcyon_live_paths": live_paths,
        "halcyon_creds": creds,
        "halcyon_local_admin_password": local_admin_pw,
        "halcyon_da_breakglass_password": da_break_glass_pw,
        "halcyon_sa_mssql_password": sa_mssql_pw,
        "halcyon_flags": flags,
    }

    SEED_OUT.parent.mkdir(parents=True, exist_ok=True)
    SEED_OUT.write_text(
        "---\n# GENERATED by gen_seed.py — do not edit, do not commit.\n"
        + yaml.safe_dump(seed_data, sort_keys=False)
    )

    ANSWER_KEY_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# Project Halcyon — Answer Key (seed: `{seed}`)\n",
        "Generated per-deploy. Do not distribute to students.\n",
        "\n## Live vulnerability paths this deployment\n",
    ]
    for p in live_paths:
        lines.append(f"- `{p}` ({vuln_paths[p]['category']})")
    lines.append("\n## Credentials\n")
    for sam, pw in creds.items():
        lines.append(f"- `{sam}` : `{pw}`")
    lines.append(f"\n- local admin (if `laps_absent_pth` live): `{local_admin_pw}`")
    lines.append(f"- MSSQL `sa`: `{sa_mssql_pw}`")
    lines.append(f"- DA break-glass: `{da_break_glass_pw}`")
    lines.append("\n## Flags\n")
    for stage, tok in flags.items():
        lines.append(f"- {stage}: `{tok}`")
    ANSWER_KEY_OUT.write_text("\n".join(lines) + "\n")

    print(f"[gen_seed] seed={seed}")
    print(f"[gen_seed] live_paths={live_paths}")
    print(f"[gen_seed] wrote {SEED_OUT}")
    print(f"[gen_seed] wrote {ANSWER_KEY_OUT}")


if __name__ == "__main__":
    sys.exit(main())
